In [14]:
import numpy as np
import pandas as pd
import math
from scipy import stats
import statistics
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold

In [7]:
dataset = pd.read_csv('credit_data.csv')
dataset.dropna(inplace = True)
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [11]:
X = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 4].values
X, y

(array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
        [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
        [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
        ...,
        [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
        [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
        [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]]),
 array([0, 0, 0, ..., 1, 0, 0], dtype=int64))

Normalização dos valores (deixar na mesma escala):

In [12]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [20]:
X

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

Variação de seleção de atributos:

In [18]:
selecao = VarianceThreshold(threshold = 0.027)
X_novo = selecao.fit_transform(X)
X_novo

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

Manteve na base de dados os dois atributos com maior variância

In [16]:
np.var(X[0]), np.var(X[1]), np.var(X[2])

(0.027646353650092187, 0.05741515340722347, 0.028389480276199003)

Menor variância vem do atributo [0], logo colocamos seu valor no threshold

Classificação:

In [21]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
naive_sem_selecao = GaussianNB()
naive_sem_selecao.fit(X, y)
previsoes = naive_sem_selecao.predict(X)
accuracy_score(previsoes, y)

0.9253880821231848

In [23]:
naive_com_selecao = GaussianNB()
naive_com_selecao.fit(X_novo, y)
accuracy_score(naive_com_selecao.predict(X_novo), y)

0.8472709063595393

Neste caso, os dados sem selação apresentaram melhor resultado, porém é recomendado usar seleção quando houver uma base de dados com muitos atributos.